# Generated by Django 4.2.3 on 2023-08-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_profile_image_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
